function getFrontmostWindow()
  return hs.window.frontmostWindow()
end

function getScreenFrame()
  return getFrontmostWindow():screen():frame()
end

function setFrontmostFrame(x, y, w, h)
  local f = getFrontmostWindow():frame()
  

  f.x = x
  f.y = y
  f.w = w
  f.h = h

  hs.window.frontmostWindow():setFrame(f)
end

function frontmostWindowAddSize(addW, addH)
  local f = getFrontmostWindow():frame()
  setFrontmostFrame(f.x, f.y, f.w + addW, f.h + addH)
end

function frontmostWindowMove(moveX, moveY)
  local f = getFrontmostWindow():frame()
  setFrontmostFrame(f.x + moveX, f.y + moveY, f.w, f.h)
end


hs.hotkey.bind({"ctrl", "alt"}, "Left", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w / 2, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "h", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w / 2, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "Right", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 2), getScreenFrame().y, getScreenFrame().w / 2, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "l", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 2), getScreenFrame().y, getScreenFrame().w, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "Up", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "Down", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y + (getScreenFrame().h / 2), getScreenFrame().w, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "Return", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "u", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w / 2, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "i", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 2), getScreenFrame().y, getScreenFrame().w / 2, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "j", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y + (getScreenFrame().h / 2), getScreenFrame().w / 2, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "k", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 2), getScreenFrame().y + (getScreenFrame().h / 2), getScreenFrame().w / 2, getScreenFrame().h / 2)
end)
hs.hotkey.bind({"ctrl", "alt"}, "m", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y + ((getScreenFrame().h / 4) * 3), getScreenFrame().w, getScreenFrame().h / 4)
end)
hs.hotkey.bind({"ctrl", "alt"}, "n", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y + ((getScreenFrame().h / 4) * 3), getScreenFrame().w / 2, getScreenFrame().h / 4)
end)
hs.hotkey.bind({"ctrl", "alt"}, ",", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 2), getScreenFrame().y + ((getScreenFrame().h / 4) * 3), getScreenFrame().w / 2, getScreenFrame().h / 4)
end)
hs.hotkey.bind({"ctrl", "alt"}, "1", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w / 3, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "2", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 3), getScreenFrame().y, getScreenFrame().w / 3, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "3", function()
  setFrontmostFrame(getScreenFrame().x + ((getScreenFrame().w / 3) * 2), getScreenFrame().y, getScreenFrame().w / 3, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "4", function()
  setFrontmostFrame(getScreenFrame().x, getScreenFrame().y, getScreenFrame().w / 4, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "5", function()
  setFrontmostFrame(getScreenFrame().x + (getScreenFrame().w / 4), getScreenFrame().y, getScreenFrame().w / 4, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "6", function()
  setFrontmostFrame(getScreenFrame().x + ((getScreenFrame().w / 4) * 2), getScreenFrame().y, getScreenFrame().w / 4, getScreenFrame().h)
end)
hs.hotkey.bind({"ctrl", "alt"}, "7", function()
  setFrontmostFrame(getScreenFrame().x + ((getScreenFrame().w / 4) * 3), getScreenFrame().y, getScreenFrame().w / 4, getScreenFrame().h)
end)

hs.hotkey.bind({"ctrl", "alt", "shift"}, "h", function()
  frontmostWindowMove(-100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "Left", function()
  frontmostWindowMove(-100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "j", function()
  frontmostWindowMove(0, -100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "Up", function()
  frontmostWindowMove(0, -100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "k", function()
  frontmostWindowMove(0, 100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "Down", function()
  frontmostWindowMove(0, 100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "l", function()
  frontmostWindowMove(100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift"}, "Right", function()
  frontmostWindowMove(100, 0)
end)

hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "h", function()
  frontmostWindowAddSize(-100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "Left", function()
  frontmostWindowAddSize(-100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "j", function()
  frontmostWindowAddSize(0, -100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "Up", function()
  frontmostWindowAddSize(0, -100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "k", function()
  frontmostWindowAddSize(0, 100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "Down", function()
  frontmostWindowAddSize(0, 100)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "l", function()
  frontmostWindowAddSize(100, 0)
end)
hs.hotkey.bind({"ctrl", "alt", "shift", "command"}, "Right", function()
  frontmostWindowAddSize(100, 0)
end)

hs.hotkey.bind({"ctrl", "alt"}, "f", function()
  if getFrontmostWindow():isFullScreen() then
    getFrontmostWindow():setFullScreen(false)
  else
    getFrontmostWindow():setFullScreen(true)
  end
end)

hs.hotkey.bind({"ctrl", "alt", "cmd"}, "Left", function()
  getFrontmostWindow():moveOneScreenWest()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "h", function()
  getFrontmostWindow():moveOneScreenWest()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "Right", function()
  getFrontmostWindow():moveOneScreenEast()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "l", function()
  getFrontmostWindow():moveOneScreenEast()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "Up", function()
  getFrontmostWindow():moveOneScreenNorth()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "k", function()
  getFrontmostWindow():moveOneScreenNorth()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "j", function()
  getFrontmostWindow():moveOneScreenSouth()
end)

